name: flutter_pokemon_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animate_do: ^4.2.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  just_audio: ^0.10.5
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
